# Default values for k8s-helm-demo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  tag: 1.16.1-alpine
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

zookeeper:
  replicaCount: 3
