apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-conf.fullname" . }}
  labels:
    {{- include "nginx-conf.labels.full" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- .Files.Get "conf-files/nginx.conf" | nindent 4 }}
