apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-conf.fullname" . }}
  labels:
    {{- include "nginx-conf.labels.full" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nginx-conf.labels.basic" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-conf.labels.basic" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-80
              containerPort: 80
            - name: http-8080
              containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: main-conf-volume
              subPath: "nginx.conf"
              readOnly: true
            - mountPath: "/etc/nginx/conf.d/"
              name: dir-conf-volume
              readOnly: true
      volumes:
        - name: main-conf-volume
          configMap:
            name: {{ include "nginx-conf.fullname" . }}-main
        - name: dir-conf-volume
          configMap:
            name: {{ include "nginx-conf.fullname" . }}-dir

