apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-helm-demo-chart.fullname" . }}
  labels:
    {{- include "k8s-helm-demo-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-helm-demo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-helm-demo-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-80
              containerPort: 80
            - name: http-8080
              containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: nginx-conf-volume
              subPath: "nginx.conf"
              readOnly: true
            - mountPath: "/etc/nginx/conf.d/"
              name: nginx-conf-d-volume
              readOnly: true
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: {{ include "k8s-helm-demo-chart.fullname" . }}-nginx-conf
        - name: nginx-conf-d-volume
          configMap:
            name: {{ include "k8s-helm-demo-chart.fullname" . }}-nginx-conf-d

